### PR TITLE
Urllib3 request hook

### PR DESCRIPTION
**Pull request by ItayGibel-helios**
# Description

Adding an option for an extended form of Urllib3 request hook with additional two arguments:
1. headers - a dictionary containing the request headers
2. body - a string containing the encoded request body 

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

Added a unit test named `test_extended_request_hook` testing the extended arguments

# Does This PR Require a Core Repo Change?
 - No.

# Checklist:

See [contributing.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md) for styleguide, changelog guidelines, and more.

- [X] Followed the style guidelines of this project
- [X] Changelogs have been updated
- [X] Unit tests have been added
- [ ] Documentation has been updated

### CODE REVIEW

**Review by nozik — APPROVED** [review]
Looks great. Please don't merge this PR - but rather open a PR to the upstream repository.

**Comment by ItayGibel-helios** [comment]
@nozik 
I added a new commit
after an [OTEL reviewer commented on my PR](https://github.com/open-telemetry/opentelemetry-python-contrib/pull/660#discussion_r701824971) and said it is ok to break the existing code - I made my _ExtenededRequestHookT type the only supported hook type

**Comment by nozik** [comment]
@ItayGibel-heliosphere 👍

**Comment by ItayGibel-helios** [comment]
Merged in the original repo

**Pull request closed without merging**
